site:
  title: Google Earth Plugin Manual
  url:  https://nowhere.net
  start_page: googleearth:ROOT:googleearth.adoc

content:
  sources:
    - url: ..
      start_path: manual
      branches: HEAD
      edit_url: https://github.com/opencpn-manuals/gecomapi_pi/edit/master/{path}

ui:   
  bundle:
    url: https://gitlab.com/leamas/antora-ui-default/-/raw/master/latest/ui-bundle.zip
    snapshot: true

output:
  dir: ./docs
  clean: true              
