/* Autogenerated by png2wx.pl on Sun Mar 13 21:37:53 2011 */
#ifndef ICONS_H
#define ICONS_H 1

#include <wx/wxprec.h>
#ifndef WX_PRECOMP
#	include <wx/wx.h>
#endif

extern void initialize_images(void);

extern wxBitmap *_img_gecomapi;
extern wxBitmap *_img_gecomapi_pi;

#ifdef GECOMAPI_USE_SVG
extern wxString _svg_gecomapi;
extern wxString _svg_gecomapi_rollover;
extern wxString _svg_gecomapi_toggled;
#endif

#endif /* ICONS_H */
