/* Autogenerated by png2wx.pl on Sun Mar 13 21:37:53 2011 */
#ifndef ICONS_H
#define ICONS_H 1

#include <wx/wxprec.h>
#ifndef WX_PRECOMP
#	include <wx/wx.h>
#endif

extern void initialize_images(void);

extern wxBitmap *_img_gecomapi;
extern wxBitmap *_img_gecomapi_pi;

#endif /* ICONS_H */
